# Tournament Simulation Analysis

## Libraries

In [1]:
import math
import pandas as pd

In [7]:
# Library settings.
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 2000)

## Data

### Retrieval

In [8]:
# Get tournament teams.
teams = pd.read_csv('../../../data/tournament_brackets/teams.csv')
# Get simulation outcomes.
outcomes_tournament = teams.merge(pd.read_csv('../../../data/simulations/tournament/agg_outcomes.csv'), on='team')
# Get matchups.
matchups_tournament = pd.read_csv('../../../data/simulations/tournament/agg_matchups.csv')

### Cleanup

In [4]:
# Store static list of column round team counts.
round_teams = [64,32,16,8,4,2]

In [5]:
# Sort by round reached and discard.
outcomes_tournament.sort(['round_reached','team'], ascending=True, inplace=True)
# outcomes_tournament.drop('round_reached', axis=1, inplace=True)
outcomes_tournament.reset_index(drop=True, inplace=True)
# Tranform wins to percentages.
win_cols = [c for c in outcomes_tournament.columns if c.startswith('wins_')]
for c, team_count in zip(win_cols,round_teams):
    outcomes_tournament[c] = 100 * outcomes_tournament[c] / 20000.
    outcomes_tournament.rename(columns={c:'round_'+str(team_count)}, inplace=True)

---

## Analysis

In [6]:
# Print outcomes.
outcomes_tournament

,team,seed,round_reached,round_64,round_32,round_16,round_8,round_4,round_2
0,Duke,1,1,97.900,83.350,59.795,35.725,18.375,6.510
1,Wisconsin,1,2,98.040,89.435,75.295,48.530,24.740,16.095
2,Kentucky,1,4,99.605,94.005,87.730,73.665,47.845,34.700
3,Michigan St.,7,4,66.735,18.965,10.325,3.110,0.930,0.220
4,Arizona,2,8,98.775,84.380,68.725,36.685,16.805,10.045
5,Gonzaga,2,8,96.990,76.690,53.815,31.150,15.595,5.400
6,Louisville,4,8,79.850,32.200,7.145,2.270,0.660,0.165
7,Notre Dame,3,8,93.220,67.095,43.015,11.880,3.995,1.770
8,North Carolina,4,16,86.245,60.220,15.095,5.215,1.350,0.440
9,North Carolina St.,8,16,55.960,7.090,2.440,0.525,0.120,0.010
10,Oklahoma,3,16,90.945,62.320,23.080,7.735,2.820,0.740
11,UCLA,11,16,35.045,9.745,2.195,0.470,0.100,0.005
12,Utah,5,16,74.270,53.055,22.375,10.700,4.215,1.055
13,West Virginia,5,16,64.485,40.390,4.380,1.450,0.265,0.075
14,Wichita St.,7,16,71.895,39.800,18.745,3.850,1.125,0.375
15,Xavier,6,16,58.675,24.890,4.915,1.045,0.160,0.045
16,Arkansas,5,32,79.275,31.950,5.430,1.285,0.245,0.045
17,Butler,6,32,45.700,14.020,5.270,0.780,0.085,0.030
18,Cincinnati,8,32,56.015,3.770,1.955,0.595,0.080,0.025
19,Dayton,11,32,39.790,12.425,2.290,0.345,0.035,0.000
20,Georgetown,4,32,85.230,32.885,9.140,2.800,0.790,0.085
21,Georgia St.,14,32,18.585,5.960,0.655,0.085,0.005,0.000
22,Iowa,7,32,49.760,11.090,4.660,1.445,0.320,0.050
23,Kansas,2,32,86.910,47.610,22.090,4.610,1.240,0.390
24,Maryland,4,32,65.630,31.005,3.025,0.880,0.175,0.025
25,Northern Iowa,5,32,89.290,62.130,18.795,7.995,3.220,0.835
26,Ohio St.,10,32,58.045,10.040,4.970,1.100,0.200,0.055
27,Oregon,8,32,50.255,5.070,1.780,0.340,0.060,0.010
28,San Diego St.,8,32,52.305,9.675,3.565,0.980,0.275,0.055
29,UAB,14,32,7.590,1.300,0.110,0.005,0.000,0.000
30,Villanova,1,32,98.335,87.835,69.680,47.155,30.250,12.845
31,Virginia,2,32,96.190,74.885,56.145,28.850,16.305,6.100
32,Albany,14,64,9.055,1.575,0.105,0.000,0.000,0.000
33,Baylor,3,64,81.415,54.665,16.310,4.515,1.065,0.400
34,Belmont,15,64,3.810,0.630,0.120,0.005,0.000,0.000
35,Buffalo,12,64,35.515,17.395,1.250,0.265,0.035,0.005
36,Coastal Carolina,16,64,1.960,0.275,0.050,0.005,0.005,0.000
37,Davidson,10,64,50.240,11.850,4.520,1.220,0.315,0.070
38,Eastern Washington,13,64,14.770,1.605,0.165,0.025,0.005,0.000
39,Georgia,10,64,33.265,5.520,1.965,0.330,0.090,0.020
40,Hampton,16,64,0.395,0.020,0.000,0.000,0.000,0.000
41,Harvard,13,64,13.755,4.270,0.285,0.020,0.000,0.000
42,Indiana,10,64,28.105,10.450,2.855,0.390,0.055,0.000
43,Iowa St.,3,64,92.410,62.830,26.670,11.785,4.375,0.995
44,LSU,9,64,44.040,4.825,1.500,0.260,0.025,0.000
45,Lafayette,16,64,1.665,0.250,0.050,0.005,0.000,0.000
46,Mississippi,11,64,41.325,14.485,2.355,0.370,0.055,0.025
47,New Mexico St.,15,64,13.090,2.140,0.335,0.015,0.000,0.000
48,North Dakota St.,15,64,3.010,0.370,0.035,0.005,0.000,0.000
49,Northeastern,14,64,6.780,1.130,0.195,0.020,0.000,0.000
50,Oklahoma St.,9,64,49.745,5.220,1.820,0.365,0.060,0.010
51,Providence,6,64,60.210,23.680,5.970,1.365,0.360,0.055
52,Purdue,9,64,43.985,2.205,0.945,0.235,0.035,0.005
53,Robert Morris,16,64,2.100,0.195,0.025,0.005,0.000,0.000
54,SMU,6,64,64.955,26.125,7.995,2.555,0.590,0.120
55,St. John's,9,64,47.695,6.780,2.110,0.400,0.060,0.005
56,Stephen F. Austin,12,64,25.730,12.455,2.825,0.730,0.160,0.025
57,Texas,11,64,54.300,17.755,7.495,1.200,0.240,0.055
58,Texas Southern,15,64,1.225,0.070,0.005,0.005,0.000,0.000
59,UC Irvine,13,64,20.150,3.315,0.240,0.030,0.010,0.000
60,VCU,7,64,41.955,5.510,2.065,0.415,0.070,0.010
61,Valparaiso,13,64,34.370,11.210,0.715,0.165,0.005,0.000
62,Wofford,12,64,20.725,3.560,0.245,0.020,0.000,0.000
63,Wyoming,12,64,10.710,2.355,0.150,0.020,0.000,0.000

Also print an HTML version for our report:

In [ ]:
# Traverse all teams.
for team in outcomes_tournament.values:
    print '<tr><td style="text-align: right"><small style="color:gray;font-size:.625em">('+str(team[1])+')</small> <strong>'+team[0]+'</strong></td>',
    # Traverse rounds.
    for result,team_count in zip(team[3:],round_teams):
        if (team_count > team[2]):
            print '<td style="text-align: center; color: green">',
        else:
            print '<td style="text-align: center; color: red">',
        if result >= 9.5:
            print '%d%%' % round(result),
        elif result >= 0.05:
            print '%.1f%%' % result,
        elif result > 0:
            print '&lt;0.1%',
        else:
            print '0%',
        print '</td>',
    print '</tr>'